### ISSUE TITLE
gibbs lda predict cannot scale out

### ISSUE THREAD

**Issue by dding3** [intel-analytics/TopicModeling#4]
The issue is reported from one of our customer. With 200W topic, 500W terms, there is OOM when doing predict.

**Comment by rql123** [comment]
@dding3 , we encountered a problem in the new predict function:

Exception in thread "main" org.apache.spark.SparkException: RDD transformations and actions can only be invoked by the driver, not inside of other transformations; for example, rdd1.map(x => rdd2.values.count() * x) is invalid because the values transformation and count action cannot be performed inside of the rdd1.map transformation. For more information, see SPARK-5063.
        at org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$sc(RDD.scala:87)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:286)
        at org.apache.spark.rdd.PairRDDFunctions.partitionBy(PairRDDFunctions.scala:493)
        at org.apache.spark.graphx.impl.VertexRDDImpl.leftJoin(VertexRDDImpl.scala:176)
        at org.apache.spark.graphx.impl.GraphImpl.outerJoinVertices(GraphImpl.scala:283)
        at org.apache.spark.mllib.topicModeling.GibbsLDAModel.predict(GibbsLDAOptimizer.scala:516)

code at GibbsLDAOptimizer.scala:516
 var corpus = previousCorpus.outerJoinVertices(ttc) { (vid, c, v) =>
      if (vid >= 0) {
        assert(v.isDefined)
      }
      v.getOrElse(c)
    }

config:
--driver-memory 30g
--executor-memory 100g
--executor-cores 100
--num-executors 100
--parallel 200
--optimizer gibbs
--k 1000000
--maxIterations 50
--vocabSize 452777
--partitions 200 
--gibbs.edgePartitioner docIdCluster 
--gibbs.sampler alias

LiuQing

**Comment by dding3** [comment]
It's not a bug of predict. 
From the description we can know the exception is caused by sparkcontex of rdd is null. From the callstack we can see the exception happend in predict and in predict there is a graph.outerjoinvertices operation. when the exception happened sparkcontext of ttc(rdd joined with graph) is null. 

We synced with customer about how they call predict in their application and knew they add persist ldamodel after training and load it before predict. The problem is ttc(rdd) is one member of  ldamodel and its sparkcontext will not persist to disk as it has been marked as transient.So after load ldamodel from disk, sparkcontext of ttc is null and there is exception.

Actually we can only persist ttc and gtc which are the most important members in ldamodel to disk and load them, then we can new a ldamodel with ttc,gtc etc and call predict.
